title: Triad Guild ROâ„¢
description: Ragnarok Mobile Triad Guild
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
github:
    zip_url: https://drive.google.com/file/d/1JkYEFH002wjdMZqI0kRsi11wjHrXnMUo/view?usp=sharing